name: Build and Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build Docker image
      run: |
        IMAGE_NAME=ghcr.io/georgehowardskub/geonews:latest
        docker build -t $IMAGE_NAME .
        echo "Built $IMAGE_NAME"

    - name: Push to GHCR
      run: |
        IMAGE_NAME=ghcr.io/georgehowardskub/geonews:latest
        docker push $IMAGE_NAME

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}

    - name: Deploy to EKS
      run: |
        kubectl set image deployment/geonews-deployment geonews=ghcr.io/${{ github.repository }}:latest
        kubectl rollout status deployment/geonews-deployment
